name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Asia/Kolkata

          base: header, activity, community, repositories, metadata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_streak: yes
          plugin_streak_days: 365
          plugin_streak_threshold: 0

          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: yes

          plugin_anilist: yes
          plugin_anilist_user: ${{ secrets.ANILIST_USER }}
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 2

          config_order: base.header, isocalendar, streak, languages, 16personalities, anilist

      - name: Commit and push metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update GitHub metrics" || echo "No changes to commit"
          git push
