name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Asia/Kolkata

          base: header, activity, community, repositories, metadata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_streak: yes
          plugin_streak_days: 365
          plugin_streak_threshold: 0

          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_limit: 5
          plugin_wakatime_user: ${{ secrets.WAKATIME_USER }}

          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: yes

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_limit: 5
          plugin_music_mode: recent

          config_order: base.header, isocalendar, streak, languages, wakatime, 16personalities, music
